import test from "node:test";
import assert from "node:assert/strict";
import {inboxPlan,submitToAuthorizedInbox} from "../src/inbox-transport.mjs";
const handoff={schema:"666CLIC_CARD_V1",source_system:"666MIRA-CORE-001",handoff_id:"666MIRA-CORE-001--sha--CARD",source_revision:"sha",authority_transfer:false,foreign_mutation:false};
const ok={explicit_scan_trigger:true,clic_write_permission:true,source_head_revalidated:true,clic_head_revalidated:true,prechange_backup_verified:true,idempotency_checked:true,clic_head:"a1"};
test("missing permissions portable fallback",()=>assert.equal(inboxPlan(handoff,{}).status,"PORTABLE_FALLBACK"));
test("unsafe path fails closed",()=>assert.equal(inboxPlan({...handoff,source_system:"../bad"},ok).status,"CONFLICT_QUARANTINE"));
test("missing authorized adapter never claims delivery",async()=>assert.equal((await submitToAuthorizedInbox(handoff,ok,null)).status,"PORTABLE_FALLBACK"));
test("failed readback never delivers",async()=>{let r=await submitToAuthorizedInbox(handoff,ok,{commitWithVerifiedBackup:async()=>({status:"COMMITTED",commit_sha:"abc",backup_verified:true,idempotency_pass:true}),readback:async()=>({matches_handoff:false,commit_sha:"abc"})});assert.equal(r.status,"NOT_VERIFIED");assert.equal(r.card_updated,false);});
test("readback verified produces receipt but no card mutation",async()=>{let r=await submitToAuthorizedInbox(handoff,ok,{commitWithVerifiedBackup:async()=>({status:"COMMITTED",commit_sha:"abc",backup_verified:true,idempotency_pass:true}),readback:async()=>({matches_handoff:true,commit_sha:"abc"})});assert.equal(r.status,"DELIVERED_VERIFIED");assert.equal(r.card_updated,false);});
